# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(671, 512)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(653, 310))
        self.tabWidget.setMaximumSize(QtCore.QSize(653, 310))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLocalize = QtWidgets.QWidget()
        self.tabLocalize.setObjectName("tabLocalize")
        self.txtCameraLightFrames = QtWidgets.QLineEdit(self.tabLocalize)
        self.txtCameraLightFrames.setGeometry(QtCore.QRect(420, 60, 113, 20))
        self.txtCameraLightFrames.setObjectName("txtCameraLightFrames")
        self.label_3 = QtWidgets.QLabel(self.tabLocalize)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.tabLocalize)
        self.label_11.setGeometry(QtCore.QRect(230, 70, 91, 21))
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(self.tabLocalize)
        self.label_6.setGeometry(QtCore.QRect(230, 40, 91, 21))
        self.label_6.setObjectName("label_6")
        self.btnLocalize = QtWidgets.QPushButton(self.tabLocalize)
        self.btnLocalize.setGeometry(QtCore.QRect(10, 240, 101, 31))
        self.btnLocalize.setObjectName("btnLocalize")
        self.roisize = QtWidgets.QSpinBox(self.tabLocalize)
        self.roisize.setGeometry(QtCore.QRect(150, 10, 71, 22))
        self.roisize.setProperty("value", 9)
        self.roisize.setObjectName("roisize")
        self.labelLocsInfo = QtWidgets.QLabel(self.tabLocalize)
        self.labelLocsInfo.setGeometry(QtCore.QRect(120, 240, 381, 31))
        self.labelLocsInfo.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelLocsInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLocsInfo.setText("")
        self.labelLocsInfo.setObjectName("labelLocsInfo")
        self.tiffPath = QtWidgets.QLineEdit(self.tabLocalize)
        self.tiffPath.setGeometry(QtCore.QRect(100, 170, 351, 20))
        self.tiffPath.setObjectName("tiffPath")
        self.gain = QtWidgets.QDoubleSpinBox(self.tabLocalize)
        self.gain.setGeometry(QtCore.QRect(310, 10, 101, 22))
        self.gain.setDecimals(4)
        self.gain.setMaximum(1000.0)
        self.gain.setProperty("value", 1.0)
        self.gain.setObjectName("gain")
        self.label_7 = QtWidgets.QLabel(self.tabLocalize)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 101, 21))
        self.label_7.setObjectName("label_7")
        self.detectionThreshold = QtWidgets.QDoubleSpinBox(self.tabLocalize)
        self.detectionThreshold.setGeometry(QtCore.QRect(151, 40, 71, 22))
        self.detectionThreshold.setDecimals(1)
        self.detectionThreshold.setProperty("value", 5.0)
        self.detectionThreshold.setObjectName("detectionThreshold")
        self.label_4 = QtWidgets.QLabel(self.tabLocalize)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 91, 21))
        self.label_4.setObjectName("label_4")
        self.startFrame = QtWidgets.QSpinBox(self.tabLocalize)
        self.startFrame.setGeometry(QtCore.QRect(100, 200, 61, 22))
        self.startFrame.setSuffix("")
        self.startFrame.setMaximum(100000000)
        self.startFrame.setProperty("value", 0)
        self.startFrame.setObjectName("startFrame")
        self.btnBrowseTiff = QtWidgets.QPushButton(self.tabLocalize)
        self.btnBrowseTiff.setGeometry(QtCore.QRect(460, 170, 141, 23))
        self.btnBrowseTiff.setObjectName("btnBrowseTiff")
        self.label_17 = QtWidgets.QLabel(self.tabLocalize)
        self.label_17.setGeometry(QtCore.QRect(10, 140, 261, 21))
        self.label_17.setObjectName("label_17")
        self.label = QtWidgets.QLabel(self.tabLocalize)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.label.setObjectName("label")
        self.btnBrowseCameraLightFrames = QtWidgets.QPushButton(self.tabLocalize)
        self.btnBrowseCameraLightFrames.setGeometry(QtCore.QRect(540, 60, 61, 23))
        self.btnBrowseCameraLightFrames.setObjectName("btnBrowseCameraLightFrames")
        self.chiSquareThreshold = QtWidgets.QDoubleSpinBox(self.tabLocalize)
        self.chiSquareThreshold.setGeometry(QtCore.QRect(270, 140, 101, 22))
        self.chiSquareThreshold.setDecimals(4)
        self.chiSquareThreshold.setProperty("value", 5.0)
        self.chiSquareThreshold.setObjectName("chiSquareThreshold")
        self.pixelsize = QtWidgets.QDoubleSpinBox(self.tabLocalize)
        self.pixelsize.setGeometry(QtCore.QRect(310, 70, 101, 22))
        self.pixelsize.setMaximum(10000.0)
        self.pixelsize.setProperty("value", 100.0)
        self.pixelsize.setObjectName("pixelsize")
        self.label_23 = QtWidgets.QLabel(self.tabLocalize)
        self.label_23.setGeometry(QtCore.QRect(20, 200, 91, 21))
        self.label_23.setObjectName("label_23")
        self.offset = QtWidgets.QDoubleSpinBox(self.tabLocalize)
        self.offset.setGeometry(QtCore.QRect(310, 40, 101, 22))
        self.offset.setMaximum(10000.0)
        self.offset.setProperty("value", 100.0)
        self.offset.setObjectName("offset")
        self.checkBoxPerPixelCamCalib = QtWidgets.QCheckBox(self.tabLocalize)
        self.checkBoxPerPixelCamCalib.setGeometry(QtCore.QRect(420, 10, 171, 17))
        self.checkBoxPerPixelCamCalib.setObjectName("checkBoxPerPixelCamCalib")
        self.btnBrowseCameraDarkFrames = QtWidgets.QPushButton(self.tabLocalize)
        self.btnBrowseCameraDarkFrames.setGeometry(QtCore.QRect(540, 30, 61, 23))
        self.btnBrowseCameraDarkFrames.setObjectName("btnBrowseCameraDarkFrames")
        self.txtCameraDarkFrames = QtWidgets.QLineEdit(self.tabLocalize)
        self.txtCameraDarkFrames.setGeometry(QtCore.QRect(420, 30, 113, 20))
        self.txtCameraDarkFrames.setObjectName("txtCameraDarkFrames")
        self.label_18 = QtWidgets.QLabel(self.tabLocalize)
        self.label_18.setGeometry(QtCore.QRect(420, 90, 211, 51))
        self.label_18.setObjectName("label_18")
        self.spinSigmaFitFramesPerBin = QtWidgets.QSpinBox(self.tabLocalize)
        self.spinSigmaFitFramesPerBin.setGeometry(QtCore.QRect(320, 100, 91, 22))
        self.spinSigmaFitFramesPerBin.setMinimum(10)
        self.spinSigmaFitFramesPerBin.setMaximum(10000)
        self.spinSigmaFitFramesPerBin.setProperty("value", 100)
        self.spinSigmaFitFramesPerBin.setObjectName("spinSigmaFitFramesPerBin")
        self.label_9 = QtWidgets.QLabel(self.tabLocalize)
        self.label_9.setGeometry(QtCore.QRect(170, 100, 141, 21))
        self.label_9.setObjectName("label_9")
        self.label_24 = QtWidgets.QLabel(self.tabLocalize)
        self.label_24.setGeometry(QtCore.QRect(180, 200, 141, 21))
        self.label_24.setObjectName("label_24")
        self.spinNumFrames = QtWidgets.QSpinBox(self.tabLocalize)
        self.spinNumFrames.setGeometry(QtCore.QRect(320, 200, 61, 22))
        self.spinNumFrames.setSuffix("")
        self.spinNumFrames.setMaximum(100000000)
        self.spinNumFrames.setProperty("value", 0)
        self.spinNumFrames.setObjectName("spinNumFrames")
        self.label_5 = QtWidgets.QLabel(self.tabLocalize)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.label_5.setObjectName("label_5")
        self.spotDetectionPSFSigma = QtWidgets.QDoubleSpinBox(self.tabLocalize)
        self.spotDetectionPSFSigma.setGeometry(QtCore.QRect(150, 70, 71, 22))
        self.spotDetectionPSFSigma.setDecimals(1)
        self.spotDetectionPSFSigma.setProperty("value", 2.0)
        self.spotDetectionPSFSigma.setObjectName("spotDetectionPSFSigma")
        self.spinSpotDetectorUseMeanImage = QtWidgets.QSpinBox(self.tabLocalize)
        self.spinSpotDetectorUseMeanImage.setGeometry(QtCore.QRect(510, 120, 71, 22))
        self.spinSpotDetectorUseMeanImage.setObjectName("spinSpotDetectorUseMeanImage")
        self.label_25 = QtWidgets.QLabel(self.tabLocalize)
        self.label_25.setGeometry(QtCore.QRect(410, 200, 91, 21))
        self.label_25.setObjectName("label_25")
        self.spinSumFrames = QtWidgets.QSpinBox(self.tabLocalize)
        self.spinSumFrames.setGeometry(QtCore.QRect(500, 200, 61, 22))
        self.spinSumFrames.setSuffix("")
        self.spinSumFrames.setMinimum(1)
        self.spinSumFrames.setMaximum(1000)
        self.spinSumFrames.setProperty("value", 1)
        self.spinSumFrames.setObjectName("spinSumFrames")
        self.tabWidget.addTab(self.tabLocalize, "")
        self.tabDriftCorrect = QtWidgets.QWidget()
        self.tabDriftCorrect.setObjectName("tabDriftCorrect")
        self.btnRCC = QtWidgets.QPushButton(self.tabDriftCorrect)
        self.btnRCC.setGeometry(QtCore.QRect(10, 10, 211, 23))
        self.btnRCC.setObjectName("btnRCC")
        self.rccFramesPerBin = QtWidgets.QSpinBox(self.tabDriftCorrect)
        self.rccFramesPerBin.setGeometry(QtCore.QRect(360, 10, 61, 21))
        self.rccFramesPerBin.setMaximum(10000)
        self.rccFramesPerBin.setProperty("value", 500)
        self.rccFramesPerBin.setObjectName("rccFramesPerBin")
        self.label_2 = QtWidgets.QLabel(self.tabDriftCorrect)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 121, 21))
        self.label_2.setObjectName("label_2")
        self.btnMinEntropyDrift = QtWidgets.QPushButton(self.tabDriftCorrect)
        self.btnMinEntropyDrift.setGeometry(QtCore.QRect(10, 40, 211, 23))
        self.btnMinEntropyDrift.setObjectName("btnMinEntropyDrift")
        self.minEntMaxSpots = QtWidgets.QSpinBox(self.tabDriftCorrect)
        self.minEntMaxSpots.setGeometry(QtCore.QRect(350, 70, 71, 21))
        self.minEntMaxSpots.setMinimum(10000)
        self.minEntMaxSpots.setMaximum(10000000)
        self.minEntMaxSpots.setProperty("value", 200000)
        self.minEntMaxSpots.setObjectName("minEntMaxSpots")
        self.minEntFramesPerBin = QtWidgets.QSpinBox(self.tabDriftCorrect)
        self.minEntFramesPerBin.setGeometry(QtCore.QRect(360, 40, 61, 21))
        self.minEntFramesPerBin.setMaximum(10000)
        self.minEntFramesPerBin.setProperty("value", 500)
        self.minEntFramesPerBin.setObjectName("minEntFramesPerBin")
        self.label_8 = QtWidgets.QLabel(self.tabDriftCorrect)
        self.label_8.setGeometry(QtCore.QRect(240, 40, 121, 21))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.tabDriftCorrect)
        self.label_10.setGeometry(QtCore.QRect(120, 70, 221, 21))
        self.label_10.setObjectName("label_10")
        self.minEntCoarseFPB = QtWidgets.QSpinBox(self.tabDriftCorrect)
        self.minEntCoarseFPB.setGeometry(QtCore.QRect(360, 100, 61, 21))
        self.minEntCoarseFPB.setMaximum(1000000)
        self.minEntCoarseFPB.setProperty("value", 0)
        self.minEntCoarseFPB.setObjectName("minEntCoarseFPB")
        self.label_12 = QtWidgets.QLabel(self.tabDriftCorrect)
        self.label_12.setGeometry(QtCore.QRect(120, 100, 221, 21))
        self.label_12.setObjectName("label_12")
        self.minEntCoarseSigmaMultiplier = QtWidgets.QDoubleSpinBox(self.tabDriftCorrect)
        self.minEntCoarseSigmaMultiplier.setGeometry(QtCore.QRect(360, 130, 61, 22))
        self.minEntCoarseSigmaMultiplier.setDecimals(4)
        self.minEntCoarseSigmaMultiplier.setMinimum(1.0)
        self.minEntCoarseSigmaMultiplier.setMaximum(1000.0)
        self.minEntCoarseSigmaMultiplier.setProperty("value", 2.0)
        self.minEntCoarseSigmaMultiplier.setObjectName("minEntCoarseSigmaMultiplier")
        self.label_13 = QtWidgets.QLabel(self.tabDriftCorrect)
        self.label_13.setGeometry(QtCore.QRect(120, 130, 221, 21))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tabDriftCorrect, "")
        self.tabPostProcess = QtWidgets.QWidget()
        self.tabPostProcess.setEnabled(False)
        self.tabPostProcess.setObjectName("tabPostProcess")
        self.btnLinkLocs = QtWidgets.QPushButton(self.tabPostProcess)
        self.btnLinkLocs.setGeometry(QtCore.QRect(160, 10, 141, 31))
        self.btnLinkLocs.setObjectName("btnLinkLocs")
        self.btnLinkLocs_2 = QtWidgets.QPushButton(self.tabPostProcess)
        self.btnLinkLocs_2.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.btnLinkLocs_2.setObjectName("btnLinkLocs_2")
        self.groupROIExtract = QtWidgets.QGroupBox(self.tabPostProcess)
        self.groupROIExtract.setGeometry(QtCore.QRect(10, 50, 621, 121))
        self.groupROIExtract.setObjectName("groupROIExtract")
        self.btnExtractROIs = QtWidgets.QPushButton(self.groupROIExtract)
        self.btnExtractROIs.setGeometry(QtCore.QRect(10, 20, 171, 23))
        self.btnExtractROIs.setObjectName("btnExtractROIs")
        self.maxLinkFrameskip = QtWidgets.QSpinBox(self.groupROIExtract)
        self.maxLinkFrameskip.setGeometry(QtCore.QRect(320, 40, 51, 22))
        self.maxLinkFrameskip.setProperty("value", 4)
        self.maxLinkFrameskip.setObjectName("maxLinkFrameskip")
        self.maxLinkDistance = QtWidgets.QDoubleSpinBox(self.groupROIExtract)
        self.maxLinkDistance.setGeometry(QtCore.QRect(320, 10, 51, 22))
        self.maxLinkDistance.setProperty("value", 0.5)
        self.maxLinkDistance.setObjectName("maxLinkDistance")
        self.label_34 = QtWidgets.QLabel(self.groupROIExtract)
        self.label_34.setGeometry(QtCore.QRect(190, 40, 111, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupROIExtract)
        self.label_35.setGeometry(QtCore.QRect(190, 10, 131, 21))
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.groupROIExtract)
        self.label_37.setGeometry(QtCore.QRect(190, 80, 101, 21))
        self.label_37.setObjectName("label_37")
        self.txtROIFile = QtWidgets.QLineEdit(self.groupROIExtract)
        self.txtROIFile.setGeometry(QtCore.QRect(310, 80, 191, 20))
        self.txtROIFile.setObjectName("txtROIFile")
        self.btnBrowseROIs = QtWidgets.QPushButton(self.groupROIExtract)
        self.btnBrowseROIs.setGeometry(QtCore.QRect(510, 80, 91, 23))
        self.btnBrowseROIs.setObjectName("btnBrowseROIs")
        self.label_36 = QtWidgets.QLabel(self.groupROIExtract)
        self.label_36.setGeometry(QtCore.QRect(380, 10, 161, 21))
        self.label_36.setObjectName("label_36")
        self.maxLinkDistanceIntensity = QtWidgets.QDoubleSpinBox(self.groupROIExtract)
        self.maxLinkDistanceIntensity.setGeometry(QtCore.QRect(540, 10, 51, 22))
        self.maxLinkDistanceIntensity.setProperty("value", 0.5)
        self.maxLinkDistanceIntensity.setObjectName("maxLinkDistanceIntensity")
        self.label_38 = QtWidgets.QLabel(self.groupROIExtract)
        self.label_38.setGeometry(QtCore.QRect(380, 40, 151, 21))
        self.label_38.setObjectName("label_38")
        self.roiExtractAppend = QtWidgets.QSpinBox(self.groupROIExtract)
        self.roiExtractAppend.setGeometry(QtCore.QRect(540, 40, 51, 22))
        self.roiExtractAppend.setProperty("value", 0)
        self.roiExtractAppend.setObjectName("roiExtractAppend")
        self.roiExtractSpotFrames = QtWidgets.QSpinBox(self.groupROIExtract)
        self.roiExtractSpotFrames.setGeometry(QtCore.QRect(120, 50, 51, 22))
        self.roiExtractSpotFrames.setProperty("value", 20)
        self.roiExtractSpotFrames.setObjectName("roiExtractSpotFrames")
        self.label_39 = QtWidgets.QLabel(self.groupROIExtract)
        self.label_39.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupROIExtract)
        self.label_40.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_40.setObjectName("label_40")
        self.roiExtractMinSpotFrames = QtWidgets.QSpinBox(self.groupROIExtract)
        self.roiExtractMinSpotFrames.setGeometry(QtCore.QRect(120, 80, 51, 22))
        self.roiExtractMinSpotFrames.setProperty("value", 20)
        self.roiExtractMinSpotFrames.setObjectName("roiExtractMinSpotFrames")
        self.tabWidget.addTab(self.tabPostProcess, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.listDatasets = QtWidgets.QListView(Dialog)
        self.listDatasets.setSizeIncrement(QtCore.QSize(1, 1))
        self.listDatasets.setObjectName("listDatasets")
        self.verticalLayout.addWidget(self.listDatasets)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnViewSelected = QtWidgets.QPushButton(self.frame)
        self.btnViewSelected.setGeometry(QtCore.QRect(10, 10, 120, 23))
        self.btnViewSelected.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btnViewSelected.setObjectName("btnViewSelected")
        self.btnLoad = QtWidgets.QPushButton(self.frame)
        self.btnLoad.setGeometry(QtCore.QRect(140, 10, 120, 23))
        self.btnLoad.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btnLoad.setObjectName("btnLoad")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Photonpy localization toolbox"))
        self.txtCameraLightFrames.setToolTip(_translate("Dialog", "Tif file with a series of light frames. Easiest is to turn the LED on your phone and record a bright field series. Regular room lighting might change the measured variance due to 50 Hz oscillations. Make sure the camera does not saturate and record about 1000 frames."))
        self.label_3.setText(_translate("Dialog", "ROI Size"))
        self.label_11.setText(_translate("Dialog", "Pixel size"))
        self.label_6.setText(_translate("Dialog", "Camera offset"))
        self.btnLocalize.setText(_translate("Dialog", "Run"))
        self.roisize.setSuffix(_translate("Dialog", " pixels"))
        self.label_7.setText(_translate("Dialog", "TIFF Path"))
        self.label_4.setText(_translate("Dialog", "Camera gain"))
        self.btnBrowseTiff.setText(_translate("Dialog", "Browse"))
        self.label_17.setText(_translate("Dialog", "Chi square threshold (filters overlapping emitters):"))
        self.label.setText(_translate("Dialog", "Detection Threshold"))
        self.btnBrowseCameraLightFrames.setText(_translate("Dialog", "Browse"))
        self.label_23.setText(_translate("Dialog", "Start frame:"))
        self.checkBoxPerPixelCamCalib.setText(_translate("Dialog", "Use per-pixel offset/gain:"))
        self.btnBrowseCameraDarkFrames.setText(_translate("Dialog", "Browse"))
        self.txtCameraDarkFrames.setToolTip(_translate("Dialog", "Enter a tif file that contains a series of completely dark frames of the camera. Should be the same size (and region) of the camera as the measurement. "))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p>Use mean frames as spot detector bg:</p><p>(0=disable)</p></body></html>"))
        self.label_9.setText(_translate("Dialog", "Gaussian sigma frames/bin:"))
        self.label_24.setText(_translate("Dialog", "Number of frames (0 for all):"))
        self.label_5.setText(_translate("Dialog", "Approx. PSF Sigma:"))
        self.spotDetectionPSFSigma.setToolTip(_translate("Dialog", "<html><head/><body><p>Approximate value for the PSF sigma (assuming 2D Gaussian PSF model). <br/>This value is only used for spot detection</p></body></html>"))
        self.label_25.setText(_translate("Dialog", "Sum frames:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLocalize), _translate("Dialog", "Localize (2D)"))
        self.btnRCC.setText(_translate("Dialog", "Redundant cross correlation (RCC)"))
        self.label_2.setText(_translate("Dialog", "Frames per bin (RCC):"))
        self.btnMinEntropyDrift.setText(_translate("Dialog", "Minimum entropy drift estimator (DME):"))
        self.label_8.setText(_translate("Dialog", "Frames per spline pt."))
        self.label_10.setText(_translate("Dialog", "Maximum number of localization to use:"))
        self.label_12.setText(_translate("Dialog", "Coarse frames per spline pt (0=disable):"))
        self.label_13.setText(_translate("Dialog", "Coarse frames sigma multiplier:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDriftCorrect), _translate("Dialog", "Drift correct"))
        self.btnLinkLocs.setText(_translate("Dialog", "Measure on time"))
        self.btnLinkLocs_2.setText(_translate("Dialog", "Export intensity traces"))
        self.groupROIExtract.setTitle(_translate("Dialog", "ROI Extraction"))
        self.btnExtractROIs.setText(_translate("Dialog", "Extract ROIs using localizations"))
        self.label_34.setText(_translate("Dialog", "Max frames skipped"))
        self.label_35.setText(_translate("Dialog", "Max distance XY (in CRLB)"))
        self.label_37.setText(_translate("Dialog", "Extracted ROIs file:"))
        self.btnBrowseROIs.setText(_translate("Dialog", "Browse"))
        self.label_36.setText(_translate("Dialog", "Max distance intensity (in CRLB)"))
        self.label_38.setText(_translate("Dialog", "Append frames front and end"))
        self.label_39.setText(_translate("Dialog", "Max spot frames:"))
        self.label_40.setText(_translate("Dialog", "Min spot frames:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPostProcess), _translate("Dialog", "Post process"))
        self.btnViewSelected.setText(_translate("Dialog", "View selected"))
        self.btnLoad.setText(_translate("Dialog", "Load localizations"))

